CREATE TABLE IF NOT EXISTS TENANTS
(
    ID           BIGSERIAL                PRIMARY KEY,
    APP_ID       BIGINT                   NOT NULL,
    GITHUB_LOGIN VARCHAR                  NOT NULL,
    GITHUB_ID    BIGINT                   NOT NULL,
    BLOCK_LIST   TEXT    DEFAULT ''       NOT NULL,
    CAPTCHA      BOOLEAN DEFAULT FALSE    NOT NULL
);

CREATE TABLE IF NOT EXISTS WECHAT_WORKS
(
    ID        BIGSERIAL             PRIMARY KEY,
    TENANT_ID BIGINT                NOT NULL,
    CORP_ID   VARCHAR               NOT NULL,
    AGENT_ID  BIGINT                NOT NULL,
    SECRET    VARCHAR               NOT NULL,
    BOT_TOKEN TEXT DEFAULT ''       NOT NULL,
    CHAT_ID   TEXT DEFAULT ''       NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS WECHAT_WORKS_TENANT_ID_UINDEX
    ON WECHAT_WORKS (TENANT_ID);

