name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  
          registry: docker.pkg.github.com
          repository: docker.pkg.github.com/${{ github.repository }}/pipehub
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
