name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/pipehub
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
